### ISSUE TITLE
actionBar设置居中不生效

### ISSUE THREAD

**Issue by Atomzzm** [plus-pro-components/plus-pro-components#158]
### plus-pro-components 版本

v0.1.4

### vue 版本

3.4.27

### element-plus 版本

2.7.2

### 最小复现环境的链接

无

### 复现步骤

复制[综合表格](https://plus-pro-components.com/components/table.html#%E7%BB%BC%E5%90%88%E8%A1%A8%E6%A0%BC)源码，action-bar增加属性`        actionBarTableColumnProps: {
          headerAlign: 'center',
        }` 但未生效。plusColumn增加`    tableColumnProps: {
      headerAlign: true
    }` 是可以生效的

### 期望的行为

Align在actionBar中也生效。  其它TableColumnCtx属性未测试

### 实际的行为

Align在actionBar中未生效

### 构建工具

Vite

**Comment by l-x-f** [comment]
表格的居中只对文本行内元素生效 ,操作栏是flex 
可使用以下样式解决
```css
.plus-table .plus-table-action-bar .cell { 
    justify-content: center;
}
```
