### ISSUE TITLE
`header-align` 属性无效

### ISSUE THREAD

**Issue by KeJunMao** [plus-pro-components/plus-pro-components#58]
```ts
tableColumnProps: {
  align: 'center',
  // 表头对齐方式， 若不设置该项，则使用表格的对齐方式
  // 'header-align': 'center'
}
```

不管是用 align 还是 header-align 都无效

临时的解决方案

```css
.is-right .plus-table-column__header {
  justify-content: end;
}
.is-center .plus-table-column__header {
  justify-content: center;
}
```

感谢您辛苦的付出！
